### ISSUE TITLE
Duplicated content in section 7 - Opcodes

### ISSUE THREAD

**Issue by Jesserc** [shafu0x/evm-from-scratch-book#13]
There are two 'Implementation' sub-sections in section 7 - Opcodes, where the second one starts [here](https://github.com/shafu0x/evm-from-scratch-book/blob/ced7040505ca10cf20964c9b91f15026442b4168/content/07_opcodes.ipynb#L484) (line 484).

This was referenced in #12 (content/07_opcodes.ipynb)

**Comment by shafu0x** [comment]
thanks for this!

should be fixed by this https://github.com/shafu0x/evm-from-scratch-book/commit/0ad793407979915bd05989a9d4cfbc97c6b9a2b9
